name: Build and Release APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - run: ./gradlew assembleDebug

      - name: Generate tag
        id: tag
        run: |
          DATE=$(date +'%Y-%m-%d')
          echo "TAG_NAME=nightly-$DATE-$GITHUB_RUN_NUMBER" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.TAG_NAME }}  # Обязательное поле
          name: "Nightly Build (${{ steps.tag.outputs.TAG_NAME }})"
          body: "Automatic build from GitHub Actions"
          files: app/build/outputs/apk/debug/app-debug.apk
          draft: false
          prerelease: true
          generate_release_notes: true
